### ISSUE TITLE
I can't figure out how this code is working,it is for greatest common divisor.

### ISSUE THREAD

**Issue by S1xnin9** [Java-Techie-jt/devops-automation#8]
![PXL_20221005_005552397.jpg](https://user-images.githubusercontent.com/115029214/193910789-817d995e-0083-411f-8ee7-7a81df1b4858.jpg)

**Comment by neeraj3199** [comment]
i can do it ....

**Comment by UmakanthSahu** [comment]
Hi @S1xnin9,

The program is correct for GCD. Its the Euclid's Algorithm for calculating GCD....

[Euclid's Algorithm](https://en.wikipedia.org/wiki/Greatest_common_divisor#Euclid's_algorithm)
You can check out this article so that you can get an idea of it.

**Comment by S1xnin9** [comment]
> Hi @S1xnin9,
> 
> The program is correct for GCD. Its the Euclid's Algorithm for calculating GCD....
> 
> [Euclid's Algorithm](https://en.wikipedia.org/wiki/Greatest_common_divisor#Euclid's_algorithm)
> You can check out this article so that you can get an idea of it. 

Thank you @UmakanthSahu .
